name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  blackbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Run service under test
        run: yarn --cwd examples/service-under-test start

      - name: Run Tests
        run: yarn --cwd examples/tests-runner test:example
